// tools/themes/abstracto.mjs
// Listas curativas de palabras por tema (conocimiento, tiempo y abstracciones).

export const abstracto = {
  Ciencia: [
    'ciencia', 'saber', 'conocimiento', 'teoría', 'hipótesis', 'tesis', 'ley', 'principio', 'postulado', 'axioma',
    'método', 'proceso', 'experimento', 'prueba', 'ensayo', 'medición', 'medida', 'cálculo', 'análisis', 'resultado',
    'dato', 'fórmula', 'ecuación', 'variable', 'constante', 'función', 'derivada', 'integral', 'matriz', 'vector',
    'número', 'cifra', 'símbolo', 'gráfica', 'tabla', 'estadística', 'probabilidad', 'aleatorio', 'promedio', 'media',
    'física', 'masa', 'peso', 'fuerza', 'energía', 'trabajo', 'potencia', 'presión', 'temperatura', 'calor',
    'frío', 'hielo', 'vapor', 'líquido', 'gaseoso', 'sólido', 'densidad', 'volumen', 'velocidad', 'aceleración',
    'gravedad', 'inercia', 'momento', 'rotación', 'fricción', 'tensión', 'flexión', 'onda', 'frecuencia', 'amplitud',
    'partícula', 'átomo', 'molécula', 'protón', 'neutrón', 'electrón', 'núcleo', 'quark', 'ion', 'isótopo',
    'elemento', 'tabla', 'periódico', 'metal', 'gas', 'líquido', 'ácido', 'base', 'sal', 'óxido',
    'reacción', 'catálisis', 'mezcla', 'compuesto', 'expansión', 'química', 'concentración', 'disolución', 'precipitado', 'cristal',
    'biología', 'célula', 'tejido', 'órgano', 'gen', 'cromosoma', 'dna', 'adn', 'proteína', 'enzima',
    'virus', 'bacteria', 'hongo', 'microbio', 'parásito', 'insecticida', 'ecosistema', 'hábitat', 'población', 'especie',
    'evolución', 'mutación', 'selección', 'natural', 'fósil', 'esqueleto', 'botánica', 'zoología', 'genética', 'anatomía',
    'materia', 'espacio', 'tiempo', 'universo', 'cosmos', 'energía', 'entropía', 'vacío', 'cuántica', 'relatividad',
    'astrofísica', 'componente', 'inflación', 'singularidad', 'gravedad', 'radiación', 'ionización', 'espectro', 'luz', 'luminosidad',
  ],

  Medicina: [
    'medicina', 'médico', 'doctor', 'medicamento', 'remedio', 'pastilla', 'píldora', 'cápsula', 'jarabe', 'gotas',
    'inyección', 'vacuna', 'suero', 'antídoto', 'anestesia', 'anestésico', 'analgesia', 'antibiótico', 'antigripal', 'antiinflamatorio',
    'analgésico', 'antihistamínico', 'antipirético', 'relajante', 'sedante', 'tranquilizante', 'laxante', 'diurético', 'vitamina', 'mineral',
    'enfermedad', 'dolencia', 'padecimiento', 'mal', 'infección', 'inflamación', 'alergia', 'asma', 'gripe', 'resfriado',
    'tos', 'fiebre', 'escalofrío', 'dolor', 'doloroso', 'picazón', 'comezón', 'mareo', 'náusea', 'vómito',
    'diarrea', 'estreñimiento', 'hernia', 'úlcera', 'gastritis', 'reflujo', 'diabetes', 'colesterol', 'hipertensión', 'presión',
    'roca', 'latido', 'angina', 'infarto', 'derrame', 'trombosis', 'epilepsia', 'migraña', 'jaqueca', 'insomnio',
    'depresión', 'ansiedad', 'pánico', 'fobia', 'manía', 'delirio', 'neurosis', 'psicosis', 'esquizofrenia', 'autismo',
    'cáncer', 'tumor', 'quiste', 'benigno', 'maligno', 'metástasis', 'quimioterapia', 'radioterapia', 'cirugía', 'operación',
    'trasplante', 'injerto', 'amputación', 'biopsia', 'análisis', 'diagnóstico', 'pronóstico', 'síntoma', 'signo', 'examen',
    'exploración', 'radiografía', 'rayos', 'resonancia', 'tomografía', 'ecografía', 'electrocardiograma', 'endoscopia', 'colonoscopia', 'densitometría',
    'tratamiento', 'terapia', 'rehabilitación', 'fisioterapia', 'quiropráctica', 'homeopatía', 'medicina', 'autocuidado', 'higiene', 'saneamiento',
    'curar', 'sanar', 'recuperar', 'cicatrizar', 'aliviar', 'prevenir', 'vacunar', 'vaciar', 'operar', 'trasplantar',
  ],

  Salud: [
    'salud', 'bienestar', 'saludable', 'sano', 'sana', 'vigor', 'vitalidad', 'energía', 'resistencia', 'fortaleza',
    'alimento', 'dieta', 'nutrición', 'nutriente', 'proteína', 'carbohidrato', 'grasa', 'fibra', 'fibra', 'hierro',
    'calcio', 'magnesio', 'potasio', 'sodio', 'zinc', 'serotonina', 'endorfinas', 'hormona', 'insulina', 'adrenalina',
    'ejercicio', 'actividad', 'movimiento', 'estiramiento', 'respiración', 'respirar', 'oxígeno', 'sueño', 'descanso', 'reposo',
    'hidratación', 'aguas', 'agua', 'abundancia', 'fruta', 'verdura', 'fibra', 'salud', 'mente', 'cuerpo',
    'equilibrio', 'armonía', 'tranquilidad', 'calma', 'serenidad', 'paz', 'plenitude', 'satisfacción', 'felicidad', 'alegría',
    'autoestima', 'confianza', 'seguridad', 'motivación', 'voluntad', 'disciplina', 'constancia', 'regularidad', 'pedir', 'hábito',
    'rutina', 'costumbre', 'normalidad', 'prevención', 'chequeo', 'control', 'revisión', 'vacunación', 'inmunidad', 'defesa',
    'defensa', 'anticuerpo', 'glóbulos', 'hemoglobina', 'vitamina', 'suplemento', 'mineral', 'nutrición', 'cerebro', 'corazón',
    'pulmón', 'riñón', 'hígado', 'piel', 'cabello', 'uñas', 'ojos', 'dientes', 'huesos', 'músculos',
    'peso', 'talla', 'índice', 'corporal', 'báscula', 'medición', 'metabolismo', 'caloría', 'grasita', 'salud',
  ],

  Clima: [
    'clima', 'tiempo', 'temperatura', 'calor', 'frío', 'tibiado', 'templado', 'cálido', 'frío', 'helado',
    'sol', 'soleado', 'bruma', 'rayo', 'relámpago', 'trueno', 'tormenta', 'tempestad', 'temporal', 'granizo',
    'lluvia', 'llovizna', 'chaparrón', 'aguacero', 'diluvio', 'monzón', 'nevada', 'nieve', 'copo', 'ventisca',
    'ventarrón', 'vendaval', 'tornado', 'huracán', 'ciclón', 'tifón', 'viento', 'brisa', 'aire', 'corriente',
    'nube', 'nublado', 'nubarrón', 'neblina', 'niebla', 'humo', 'polvo', 'arena', 'canícula', 'bochorno',
    'humedad', 'sequía', 'aridez', 'reseco', 'chubasco', 'trueno', 'granizada', 'escarcha', 'rocío', 'sereno',
    'gélido', 'polar', 'tropical', 'mediterráneo', 'desértico', 'montañoso', 'oceánico', 'continental', 'subtropical', 'ecuatorial',
    'invierno', 'verano', 'primavera', 'otoño', 'estación', 'climatología', 'meteorología', 'pronóstico', 'previsión', 'paraguas',
    'gabardina', 'impermeable', 'abrigo', 'bufanda', 'guantes', 'gorro', 'chanclas', 'hielo', 'termómetro', 'barómetro',
  ],

  Emociones: [
    'emoción', 'sentimiento', 'alegría', 'felicidad', 'gozo', 'regocijo', 'dicha', 'placer', 'deleite', 'júbilo',
    'entusiasmo', 'excitación', 'esperanza', 'optimismo', 'ilusión', 'satisfacción', 'orgullo', 'amor', 'cariño', 'afecto',
    'ternura', 'compasión', 'empatía', 'amistad', 'confianza', 'lealtad', 'gratitud', 'agradecimiento', 'admiración', 'respeto',
    'sorpresa', 'asombro', 'extrañeza', 'perplejidad', 'incertidumbre', 'curiosidad', 'interés', 'fascinación', 'nostalgia', 'melancolía',
    'añoranza', 'tristeza', 'pena', 'dolor', 'sufrimiento', 'angustia', 'desconsuelo', 'abatimiento', 'desánimo', 'frustración',
    'decepción', 'desilusión', 'fracaso', 'vergüenza', 'bochorno', 'culpa', 'remordimiento', 'arrepentimiento', 'lástima', 'pesar',
    'miedo', 'temor', 'terror', 'pánico', 'horror', 'espanto', 'fobia', 'ansiedad', 'nervios', 'preocupación',
    'inquietud', 'intranquilidad', 'zozobra', 'tensión', 'estrés', 'presión', 'desesperación', 'pánico', 'agobio', 'ahogo',
    'ira', 'enojo', 'cólera', 'rabia', 'furia', 'indignación', 'resentimiento', 'rencor', 'odio', 'desprecio',
    'envidia', 'celos', 'avaricia', 'egoísmo', 'soledad', 'vacío', 'apatía', 'indiferencia', 'aburrimiento', 'hastío',
    'calma', 'serenidad', 'tranquilidad', 'paz', 'alivio', 'confort', 'seguridad', 'tranquilo', 'afecto', 'arraigo',
  ],

  Colores: [
    'color', 'rojo', 'verde', 'azul', 'amarillo', 'negro', 'blanco', 'gris', 'marrón', 'café',
    'naranja', 'anaranjado', 'rosa', 'rojo', 'violeta', 'morado', 'púrpura', 'lila', 'fucsia', 'magenta',
    'turquesa', 'cian', 'celeste', 'añil', 'índigo', 'beige', 'claro', 'oscuro', 'crema', 'dorado',
    'plateado', 'bronce', 'granate', 'burdeos', 'esmeralda', 'oliva', 'salmón', 'coral', 'lavanda', 'menta',
    'chocolate', 'carmesí', 'escarlata', 'bermellón', 'gualda', 'sepia', 'ávido', 'multicolor', 'arco', 'iris',
    'pigmento', 'tono', 'matiz', 'tinte', 'tinta', 'pintura', 'musgo', 'blanquecino', 'negruzco', 'rojizo',
    'verdoso', 'azulado', 'amarillento', 'amarilloso', 'negrito', 'blanquito', 'rosado', 'verdigris', 'cromático', 'crominancia',
  ],

  Números: [
    'número', 'numeral', 'cifra', 'cantidad', 'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis',
    'siete', 'ocho', 'nueve', 'diez', 'once', 'doce', 'trece', 'catorce', 'quince', 'veinte',
    'treinta', 'cuarenta', 'cincuenta', 'sesenta', 'setenta', 'ochenta', 'noventa', 'diecinueve', 'cien', 'ciento',
    'doscientos', 'trescientos', 'quinientos', 'mil', 'millón', 'miríada', 'unidad', 'decena', 'centena', 'distancia',
    'doble', 'triple', 'cuádruple', 'mitad', 'tercio', 'cuarta', 'quinto', 'sexto', 'séptimo', 'octavo',
    'noveno', 'décimo', 'primero', 'segundo', 'tercero', 'cuarto', 'último', 'par', 'impar', 'primo',
    'composición', 'fracción', 'decimal', 'entero', 'natural', 'negativo', 'positivo', 'romano', 'arabe', 'arábico',
    'serie', 'secuencia', 'progresión', 'sucesión', 'numérico', 'digito', 'dígito', 'numerador', 'denominador', 'porcentaje',
    'promedio', 'mediana', 'moda', 'rango', 'suma', 'resta', 'división', 'multiplicación', 'potencia', 'raíz',
  ],

  Geometría: [
    'geometría', 'forma', 'figura', 'punto', 'línea', 'recta', 'curva', 'segmento', 'rayo', 'semirrecta',
    'plano', 'superficie', 'cuerpo', 'sólido', 'esfera', 'cubo', 'cilindro', 'cono', 'pirámide', 'prisma',
    'hexágono', 'pentágono', 'tetraedro', 'dodecaedro', 'icosaedro', 'octaedro', 'poliedro', 'paralelepípedo', 'elipsoide', 'toroide',
    'círculo', 'circunferencia', 'elipse', 'parábola', 'hipérbola', 'cuadrado', 'rectángulo', 'rombo', 'romboide', 'trapecio',
    'triángulo', 'escaleno', 'isósceles', 'equilátero', 'rectángulo', 'acutángulo', 'obtusángulo', 'polígono', 'arco', 'diámetro',
    'radio', 'cuerda', 'tangente', 'secante', 'vértice', 'ángulo', 'recto', 'agudo', 'obtuso', 'llano',
    'adyacente', 'opuesto', 'alterno', 'bisectriz', 'mediana', 'altura', 'apotema', 'perímetro', 'área', 'área',
    'diagonal', 'mediana', 'eje', 'simetría', 'traslación', 'rotación', 'reflexión', 'escalamiento', 'homotecia', 'proyección',
    'geodesia', 'cartografía', 'medir', 'trazar', 'dividir', 'calcular', 'aplicar', 'dicotomía', 'coordenada', 'plano',
  ],

  Tiempo: [
    'tiempo', 'momento', 'instante', 'segundo', 'minuto', 'hora', 'reloj', 'cronómetro', 'sabático', 'alarma',
    'amanecer', 'alba', 'aurora', 'madrugada', 'mañana', 'mediodía', 'tarde', 'atardecer', 'ocaso', 'crepúsculo',
    'noche', 'medianoche', 'madrugada', 'anochecer', 'víspera', 'ayer', 'hoy', 'mañana', 'presente', 'pasado',
    'futuro', 'mañana', 'semana', 'fin', 'día', 'sábado', 'domingo', 'lunes', 'martes', 'miércoles',
    'jueves', 'viernes', 'mes', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio',
    'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre', 'año', 'bisiesto', 'década', 'siglo', 'milenio',
    'eras', 'era', 'época', 'periodo', 'período', 'etapa', 'fase', 'ciclo', 'estación', 'temporada',
    'calendario', 'fecha', 'cita', 'plazo', 'término', 'duración', 'permanencia', 'instante', 'momento', 'ocasión',
    'pronto', 'tarde', 'temprano', 'reciente', 'antiguo', 'nuevo', 'viejo', 'moderno', 'actual', 'histórico',
    'reloj', 'péndulo', 'minutero', 'segundero', 'esfera', 'aguja', 'cronología', 'prehistoria', 'actualidad', 'efímero',
  ],

  Geografía: [
    'geografía', 'mapa', 'plano', 'globo', 'atlas', 'brújula', 'norte', 'sur', 'este', 'este',
    'oeste', 'nordeste', 'sudeste', 'noroeste', 'suroeste', 'cardinal', 'hemisferio', 'ecuador', 'trópico', 'meridiano',
    'paralelo', 'latitud', 'longitud', 'altitud', 'coordenadas', 'continente', 'península', 'istmo', 'archipiélago', 'isla',
    'islote', 'atolón', 'cabo', 'punta', 'golfo', 'bahía', 'ensenada', 'estrecho', 'canal', 'paso',
    'delta', 'estuario', 'ría', 'playa', 'costa', 'litoral', 'costa', 'acantilado', 'arrecife', 'barrera',
    'océano', 'pacífico', 'atlántico', 'índico', 'ártico', 'antártico', 'mediterráneo', 'caribe', 'mar', 'continente',
    'áfrica', 'américa', 'asia', 'europa', 'oceanía', 'antártida', 'país', 'nación', 'estado', 'ciudad',
    'capital', 'población', 'territorio', 'frontera', 'límite', 'región', 'zona', 'zona', 'área', 'extensión',
    'sierra', 'cordillera', 'macizo', 'altiplano', 'meseta', 'llanura', 'desierto', 'selva', 'sabana', 'pampa',
    'andina', 'amazónica', 'patagonia', 'andes', 'himalaya', 'alpes', 'rocosa', 'urables', 'kalahari', 'monte',
  ],

  Astronomía: [
    'astronomía', 'astro', 'estrella', 'lucero', 'sol', 'luna', 'cometa', 'meteorito', 'meteoro', 'bólido',
    'asteroide', 'planeta', 'mercurio', 'venus', 'tierra', 'marte', 'júpiter', 'saturno', 'urano', 'neptuno',
    'plutón', 'enano', 'exoplaneta', 'gigante', 'satélite', 'luna', 'luna', 'fase', 'orbita', 'órbita',
    'gravedad', 'atracción', 'centrífuga', 'espacio', 'vacío', 'cosmos', 'universo', 'galaxia', 'vía', 'láctea',
    'nebulosa', 'quásar', 'pulsar', 'agujero', 'negro', 'blanco', 'supernova', 'nova', 'enana', 'roja',
    'estructura', 'cúmulo', 'constelación', 'zodiaco', 'aries', 'tauro', 'géminis', 'cáncer', 'leo', 'virgo',
    'libra', 'escorpio', 'sagitario', 'capricornio', 'acuario', 'piscis', 'orión', 'osos', 'mayor', 'menor',
    'casio', 'perro', 'cisne', 'águila', 'cruz', 'estrella', 'estrella', 'luza', 'luz', 'años',
    'pársec', 'año', 'luz', 'astronauta', 'orbita', 'telescopio', 'observatorio', 'planetario', 'cohete', 'sonda',
    'módulo', 'nave', 'transbordador', 'lanzadera', 'vuelo', 'traje', 'espacial', 'galáctico', 'cósmico', 'estelar',
  ],

  Religión: [
    'religión', 'fe', 'creencia', 'espíritu', 'alma', 'espiritualidad', 'aducir', 'divinidad', 'deidad', 'dios',
    'diosa', 'providencia', 'creador', 'padre', 'señor', 'nesc', 'santo', 'santa', 'santidad', 'ángel',
    'arcángel', 'querubín', 'serafín', 'demonio', 'diablo', 'lucifer', 'misterio', 'dogma', 'doctrina', 'teología',
    'oración', 'rezar', 'rezo', 'plegaria', 'alabanza', 'adorar', 'adoración', 'devoción', 'piedad', 'veneración',
    'culto', 'rito', 'ritual', 'liturgia', 'ceremonia', 'sacramento', 'bautismo', 'comunión', 'eucaristía', 'confesión',
    'penitencia', 'confirmación', 'matrimonio', 'orden', 'unción', 'milagro', 'profecía', 'profeta', 'apóstol', 'discípulo',
    'evangelio', 'iglesia', 'templo', 'capilla', 'basílica', 'catedral', 'mezquita', 'sinagoga', 'pagoda', 'cristo',
    'jesús', 'maría', 'virgen', 'sagrada', 'crucifijo', 'crucificados', 'cruz', 'rosario', 'biblia', 'corán',
    'torá', 'sagradas', 'escrituras', 'génesis', 'éxodo', 'apocalipsis', 'paraíso', 'cielo', 'infierno', 'purgatorio',
    'resurrección', 'júbileo', 'navidad', 'pascua', 'cuaresma', 'adviento', 'epifanía', 'pentecostés', 'ramadán', 'navidad',
  ],

  Política: [
    'política', 'gobierno', 'estado', 'nación', 'país', 'república', 'monarquía', 'democracia', 'dictadura', 'régimen',
    'parlamento', 'congreso', 'senado', 'diputados', 'asamblea', 'legislatura', 'constitución', 'leyes', 'derecho', 'justicia',
    'tribunal', 'juzgado', 'corte', 'magistrado', 'fiscal', 'abogado', 'delito', 'castigo', 'pena', 'sentencia',
    'impuesto', 'impuestos', 'tributo', 'tribunal', 'aranceles', 'presupuesto', 'gasto', 'deuda', 'inflación', 'economía',
    'banco', 'moneda', 'billete', 'divisas', 'reforma', 'revolución', 'golpe', 'elección', 'sufragio', 'votar',
    'voto', 'electoral', 'campana', 'campaña', 'candidato', 'presidente', 'vicepresidente', 'ministro', 'gobierno', 'alcalde',
    'gobernador', 'diputado', 'senador', 'concejal', 'embajador', 'diplomático', 'canciller', 'político', 'partido', 'coalición',
    'alianza', 'oposición', 'ideología', 'derecha', 'izquierda', 'centro', 'liberal', 'conservador', 'socialista', 'comunista',
    'anarco', 'populismo', 'nacionalismo', 'globalización', 'internacional', 'tratado', 'acuerdo', 'pacto', 'embargo', 'sanciones',
  ],

  Verbos: [
    'amar', 'querer', 'odiar', 'adorar', 'respetar', 'honrar', 'cuidar', 'proteger', 'defender', 'ayudar',
    'socorrer', 'salvar', 'rescatar', 'apoyar', 'animar', 'alentar', 'consolar', 'abrazar', 'besar', 'acoger',
    'aceptar', 'admitir', 'permitir', 'consentir', 'aprobar', 'confirmar', 'verificar', 'comprobar', 'chequear', 'revisar',
    'inspeccionar', 'observar', 'mirar', 'contemplar', 'admirar', 'examinar', 'estudiar', 'analizar', 'investigar', 'indagar',
    'explorar', 'buscar', 'hallar', 'encontrar', 'descubrir', 'identificar', 'reconocer', 'recordar', 'olvidar', 'olvidarme',
    'memorizar', 'aprender', 'enseñar', 'explicar', 'aclarar', 'demostrar', 'probar', 'mostrar', 'presentar', 'exponer',
    'comunicar', 'hablar', 'decir', 'contar', 'narrar', 'relatar', 'comentar', 'conversar', 'charlar', 'dialogar',
    'preguntar', 'contestar', 'responder', 'contestar', 'pedir', 'rogar', 'suplicar', 'exigir', 'ordenar', 'mandar',
    'instruir', 'indicar', 'señalar', 'apuntar', 'orientar', 'guiar', 'conducir', 'dirigir', 'liderar', 'capitanear',
    'comandar', 'gobernar', 'administrar', 'gestionar', 'manejar', 'operar', 'usar', 'utilizar', 'emplear', 'aplicar',
    'ejercer', 'practicar', 'ejecutar', 'realizar', 'efectuar', 'hacer', 'crear', 'producir', 'fabricar', 'construir',
    'edificar', 'levantar', 'erigir', 'montar', 'armar', 'preparar', 'organizar', 'planear', 'planificar', 'proyectar',
    'disociar', 'designar', 'componer', 'estructurar', 'formular', 'idear', 'inventar', 'crear', 'diseñar', 'trazar',
    'dibujar', 'pintar', 'colorear', 'decorar', 'adornar', 'ornamentar', 'vestir', 'abrigar', 'calzar', 'peinar',
    'cocinar', 'asar', 'freír', 'hervir', 'hornear', 'guisar', 'condimentar', 'salar', 'endulzar', 'mezclar',
    'batir', 'remover', 'agitar', 'mover', 'empujar', 'tirar', 'arrastrar', 'empurar', 'levantar', 'alzar',
    'levantar', 'enaltecer', 'subir', 'escalar', 'trepar', 'descender', 'bajar', 'caer', 'derrumbar', 'desplomar',
    'saltar', 'brincar', 'correr', 'trotar', 'caminar', 'andar', 'pasear', 'recorrer', 'viajar', 'explorar',
    'llegar', 'partir', 'salir', 'irse', 'entrar', 'regresar', 'volver', 'retornar', 'venir', 'acudir',
    'asistir', 'participar', 'colaborar', 'cooperar', 'trabajar', 'laborar', 'esforzarse', 'luchar', 'pelear', 'batallar',
    'combatir', 'vencer', 'superar', 'derrotar', 'ganar', 'triunfar', 'lograr', 'conseguir', 'alcanzar', 'obtener',
    'adquirir', 'comprar', 'vender', 'pagar', 'cobrar', 'gastar', 'ahorrar', 'invertir', 'financiar', 'presupuestar',
    'comer', 'beber', 'desayunar', 'almorzar', 'cenar', 'merendar', 'picar', 'morder', 'masticar', 'tragar',
    'dormir', 'soñar', 'descansar', 'reposar', 'recuperar', 'despertar', 'levantar', 'dormirse', 'casar', 'besar',
    'llorar', 'reír', 'sonreír', 'sufrir', 'sentir', 'experimentar', 'percibir', 'notar', 'detectar', 'oler',
    'degustar', 'tocar', 'acaricar', 'tentar', 'saborear', 'escuchar', 'oir', 'oír', 'escuchar', 'cantar',
    'tararear', 'silbar', 'aplaudir', 'bailar', 'zapatear', 'girar', 'dar', 'recibir', 'tomar', 'coger',
    'agarrar', 'sostener', 'sujetar', 'soltar', 'lanzar', 'arrojar', 'tirar', 'atrapar', 'capturar', 'apresar',
    'robar', 'hurtar', 'asaltar', 'secuestrar', 'engañar', 'mentir', 'ocultar', 'esconder', 'guardar', 'esconderse',
    'romper', 'quebrar', 'destrozar', 'dañar', 'estropear', 'arreglar', 'reparar', 'componer', 'ajustar', 'calibrar',
    'limpiar', 'lavar', 'enjuagar', 'secar', 'planchar', 'barrer', 'trapear', 'aspirar', 'fregar', 'lustrar',
    'leer', 'escribir', 'redactar', 'teclear', 'firmar', 'dictar', 'copiar', 'transcribir', 'imprimir', 'publicar',
    'telefonear', 'llamar', 'tiempo', 'esperar', 'aguardar', 'esperar', 'urticar', 'precipitar', 'apresurar', 'demorar',
    'avanzar', 'progresar', 'mejorar', 'perfeccionar', 'optimizar', 'desarrollar', 'crecer', 'expandir', 'ampliar', 'extender',
    'reducir', 'disminuir', 'encoger', 'acortar', 'alargar', 'prolongar', 'estrechar', 'ensanchar', 'aumentar', 'acelerar',
    'frenar', 'detener', 'parar', 'cesar', 'finalizar', 'terminar', 'acabar', 'concluir', 'cerrar', 'clausurar',
    'abrir', 'destapar', 'iniciar', 'comenzar', 'empezar', 'principiar', 'recuperar', 'sabotear', 'obstaculizar', 'bloquear',
  ],
};