// tools/themes/naturaleza.mjs
// Listas curativas de palabras por tema (naturaleza + cuerpo humano).
// Cada palabra: minúscula, 3-12 caracteres [a-zñáéíóúü].

export const naturaleza = {
  Animales: [
    'perro', 'perra', 'cachorro', 'perrito', 'gato', 'gata', 'gatito', 'can', 'felino', 'canino',
    'caballo', 'yegua', 'potro', 'poni', 'asno', 'burro', 'mula', 'toro', 'vaca', 'buey',
    'novillo', 'ternero', 'becerro', 'oveja', 'cabra', 'chivo', 'cabrito', 'carnero', 'cordero', 'borrego',
    'cerdo', 'cochino', 'chancho', 'marrano', 'jabalí', 'verraco', 'conejo', 'cuadrúpedo', 'liebre', 'conejillo',
    'rata', 'ratón', 'hámster', 'cobaya', 'ardilla', 'castor', 'nutria', 'topo', 'erizo', 'tejón',
    'murciélago', 'lirón', 'visón', 'marmota', 'comadreja', 'suricato', 'lobo', 'zorro', 'coyote', 'chacal',
    'oso', 'panda', 'león', 'leona', 'leopardo', 'pantera', 'puma', 'jaguar', 'guepardo', 'tigre',
    'hiena', 'lince', 'elefante', 'mamut', 'rinoceronte', 'hipopótamo', 'jirafa', 'cebra', 'camello', 'dromedario',
    'llama', 'alpaca', 'vicuña', 'guanaco', 'bisonte', 'búfalo', 'rebeco', 'ciervo', 'venado', 'corzo',
    'alce', 'reno', 'gorila', 'chimpancé', 'mono', 'macaco', 'tití', 'mandril', 'babuino', 'orangután',
    'canguro', 'koala', 'wombat', 'equidna', 'ornitorrinco', 'zarigüeya', 'armadillo', 'perezoso', 'hormiguero', 'pangolín',
    'morsa', 'foca', 'león', 'delfín', 'orca', 'ballena', 'cachalote', 'narval', 'beluga', 'manatí',
    'dugongo', 'sapo', 'rana', 'renacuajo', 'tortuga', 'galápago', 'carey', 'lagarto', 'iguana', 'camaleón',
    'gecko', 'lagartija', 'serpiente', 'culebra', 'víbora', 'boa', 'pitón', 'cobra', 'cocodrilo', 'caimán',
    'aligátor', 'gavial', 'avestruz', 'ñandú', 'emú', 'casuario', 'pingüino', 'pichón', 'équido', 'bóvido',
    'félido', 'cánido', 'mamífero', 'herbívoro', 'carnívoro', 'omnívoro', 'roedor', 'marsupial', 'primate', 'ungulado',
    'cabrío', 'ovejuno', 'porcino', 'vacuno', 'equino', 'bovino', 'simio', 'reptil', 'anfibio', 'vertebrado',
  ],

  'Aves y Peces': [
    'pájaro', 'ave', 'gorrión', 'golondrina', 'cuervo', 'grajo', 'urraca', 'paloma', 'tórtola', 'pichón',
    'loro', 'cotorra', 'papagayo', 'guacamayo', 'canario', 'ruiseñor', 'mirlo', 'petirrojo', 'jilguero', 'pinzón',
    'caracara', 'cernícalo', 'aguilucho', 'águila', 'halcón', 'azor', 'milano', 'buitre', 'cóndor', 'albatros',
    'gaviota', 'gaviotín', 'garza', 'cigüeña', 'grulla', 'flamenco', 'pelícano', 'cisne', 'ganso', 'oca',
    'pato', 'ánade', 'patito', 'codorniz', 'perdigón', 'faisán', 'pavo', 'pavón', 'gallina', 'gallo',
    'pollito', 'gallo', 'tucán', 'colibrí', 'picaflor', 'búho', 'lechuza', 'autillo', 'mochuelo', 'cárabo',
    'carpintero', 'pájaro', 'martín', 'abubilla', 'chotacabras', 'vencejo', 'avión', 'urón', 'alondra', 'lavandera',
    'pechiazul', 'carbonero', 'herrerillo', 'trepador', 'pico', 'zapador', 'mirlo', 'zorzal', 'chorlito', 'avefría',
    'pecera', 'pez', 'sardina', 'atún', 'bacalao', 'lubina', 'robalo', 'merluza', 'rape', 'boquerón',
    'anchoa', 'anguila', 'congrio', 'trucha', 'salmón', 'carpa', 'perca', 'lucio', 'barbo', 'pez',
    'dorada', 'besugo', 'lenguado', 'rodaballo', 'pez espada', 'tiburón', 'tintorera', 'cazón', 'marlín', 'pez globo',
    'caballito', 'pez payaso', 'anguila', 'morena', 'mantarraya', 'pez luna', 'carpín', 'guppy', 'pirana', 'piraña',
    'orca', 'rape', 'sargo', 'jurel', 'anguila', 'pécora', 'escardó', 'salmonete', 'galápago', 'perca',
  ],

  Insectos: [
    'insecto', 'bicho', 'abeja', 'avispón', 'avispa', 'hormiga', 'termita', 'termitas', 'polilla', 'mariposa',
    'mosca', 'mosquito', 'zancudo', 'tábano', 'cucaracha', 'grillo', 'saltamontes', 'langosta', 'pulgón', 'chinche',
    'escarabajo', 'mariquita', 'luciérnaga', 'libélula', 'aguacil', 'mantis', 'cigarra', 'chinche', 'abejorro', 'mosquito',
    'piojo', 'liendre', 'garrapata', 'ácaro', 'araña', 'escorpión', 'alacrán', 'cangrejo', 'langosta', 'camarón',
    'gamba', 'langostino', 'cangrejo', 'cardumen', 'gusano', 'oruga', 'larva', 'pupas', 'crisálida', 'nido',
    'colmena', 'enjambre', 'hormiguero', 'telaraña', 'capullo', 'insecto', 'hemíptero', 'coleóptero', 'lepidóptero', 'arana',
    'ciempiés', 'milpiés', 'escolopendra', 'sanguijuela', 'babosa', 'caracol', 'mejillón', 'almeja', 'pulpo', 'calamar',
    'medusa', 'estrella', 'esponja', 'erizo', 'anémona', 'buccino', 'percebe', 'coral', 'plancton', 'zooplancton',
  ],

  'Frutas y Verduras': [
    'manzana', 'pera', 'plátano', 'mango', 'papaya', 'sandía', 'melón', 'fresa', 'fresón', 'arándano',
    'frambuesa', 'mora', 'cereza', 'guinda', 'ciruela', 'albaricoque', 'damasco', 'durazno', 'melocotón', 'nectarina',
    'uva', 'pasita', 'higo', 'chirimoya', 'granada', 'cacao', 'coco', 'guayaba', 'naranja', 'limón',
    'lima', 'mandarina', 'pomelo', 'toronja', 'kiwi', 'piña', 'ananá', 'maracuyá', 'granadilla', 'litchi',
    'mamey', 'zapote', 'tamarindo', 'parcha', 'rambután', 'dátil', 'palta', 'aguacate', 'aceituna', 'oliva',
    'tomate', 'jitomate', 'pepino', 'calabaza', 'zapallo', 'calabacín', 'zucchini', 'berenjena', 'pimiento', 'pimentón',
    'ají', 'chile', 'maíz', 'elote', 'choclo', 'mazorca', 'fríjol', 'frijol', 'haba', 'judía',
    'lenteja', 'garbanzo', 'soja', 'sésamo', 'ajonjolí', 'cacahuate', 'maní', 'nuez', 'pistacho', 'almendra',
    'avellana', 'castaña', 'coco', 'piñón', 'cebolla', 'ajo', 'chorizo', 'puerro', 'apio', 'espárrago',
    'lechuga', 'espinaca', 'acelga', 'repollo', 'col', 'brócoli', 'coliflor', 'remolacha', 'betabel', 'rábano',
    'zanahoria', 'nabo', 'chícharo', 'guisante', 'papa', 'patata', 'batata', 'camote', 'yuca', 'mandioca',
    'ñame', 'mazapán', 'chayote', 'yuca', 'alcachofa', 'cardo', 'calabaza', 'orégano', 'albahaca', 'perejil',
  ],

  'Comida y Bebida': [
    'pan', 'bollo', 'baguette', 'panecillo', 'tortilla', 'queso', 'manteca', 'mantequilla', 'nata', 'crema',
    'yogur', 'yogurt', 'leche', 'batido', 'flán', 'natilla', 'dulce', 'caramelo', 'miel', 'azúcar',
    'sal', 'salero', 'mostaza', 'mayonesa', 'ketchup', 'salsa', 'vinagre', 'aceite', 'manteca', 'margarina',
    'huevo', 'huevera', 'omelette', 'tortilla', 'mermelada', 'chocolate', 'dulce', 'turrón', 'mazapán', 'galleta',
    'pastel', 'tarta', 'bizcocho', 'magdalena', 'croissant', 'donut', 'rosquilla', 'empanada', 'pizza', 'hamburguesa',
    'perrito', 'hot dog', 'perro', 'sándwich', 'sandwich', 'taco', 'burrito', 'fajita', 'quesadilla', 'nachos',
    'burrito', 'arepa', 'sopa', 'caldo', 'guiso', 'estofado', 'puchero', 'cocido', 'potaje', 'puré',
    'croqueta', 'albóndiga', 'salchicha', 'chorizo', 'jamón', 'tocino', 'bacon', 'solomillo', 'chuleta', 'filete',
    'bistec', 'costilla', 'pavo', 'pollo', 'conejo', 'cordero', 'ternera', 'lomo', 'carne', 'pescado',
    'marisco', 'cena', 'comida', 'almuerzo', 'desayuno', 'merienda', 'aperitivo', 'menú', 'receta', 'horno',
    'freír', 'asar', 'hervir', 'cocinar', 'pastel', 'repollo', 'ensalada', 'guarnición', 'postre', 'helado',
    'paleta', 'chicle', 'golosina', 'café', 'cafecito', 'té', 'mate', 'infusión', 'smoothie', 'zumo',
    'jugo', 'agua', 'refresco', 'gaseosa', 'soda', 'cerveza', 'vino', 'sidra', 'champán', 'coñac',
    'ron', 'whisky', 'licor', 'pisco', 'tequila', 'mezcal', 'brandy', 'vermut', 'anís', 'champaña',
    'bebida', 'trago', 'cóctel', 'pisco', 'botella', 'vaso', 'taza', 'jarra', 'liquido', 'bebida',
  ],

  Naturaleza: [
    'naturaleza', 'tierra', 'suelo', 'lodo', 'barro', 'arena', 'roca', 'piedra', 'canto', 'guijarro',
    'montaña', 'monte', 'colina', 'loma', 'cerro', 'valle', 'lago', 'laguna', 'charca', 'estanque',
    'río', 'riachuelo', 'arroyo', 'manantial', 'fuente', 'cascada', 'salto', 'catarata', 'chorro', 'brazo',
    'mar', 'océano', 'golfo', 'bahía', 'costa', 'playa', 'orilla', 'ribera', 'delta', 'desembocadura',
    'bosque', 'selva', 'jungla', 'floresta', 'arboleda', 'pinar', 'robledal', 'matorral', 'maleza', 'prado',
    'campo', 'pradera', 'llanura', 'sabana', 'estepa', 'desierto', 'oasis', 'duna', 'tundra', 'taiga',
    'volcán', 'cráter', 'ceniza', 'lavado', 'geiser', 'sismicidad', 'terremoto', 'temblor', 'tornado', 'huracán',
    'remolino', 'vendaval', 'ciclón', 'barranco', 'cañón', 'cueva', 'caverna', 'gruta', 'acantilado', 'farallón',
    'arbol', 'árbol', 'roble', 'encina', 'alcornoque', 'haya', 'fresno', 'arce', 'abeto', 'pino',
    'picea', 'cedro', 'ciprés', 'sauce', 'chopo', 'álamo', 'abedul', 'olmo', 'castaño', 'nogal',
    'manzano', 'peral', 'cerezo', 'melocotonero', 'almendro', 'olivo', 'naranjo', 'limonero', 'higuera', 'parra',
    'vid', 'eucalipto', 'palmera', 'coco', 'banano', 'mango', 'baobab', 'séquoia', 'palo', 'rama',
    'hoja', 'raíz', 'tronco', 'corteza', 'fruto', 'semilla', 'flor', 'florecita', 'pétalo', 'tallo',
    'hierba', 'pasto', 'césped', 'esparto', 'musgo', 'helecho', 'mata', 'arbusto', 'matorral', 'maleza',
    'jungla', 'brote', 'yema', 'péndulo', 'jazmín', 'madreselva', 'girasol', 'margarita', 'orquídea', 'rosa',
    'rosa', 'clavel', 'tulipán', 'lirio', 'amapola', 'lavanda', 'peonía', 'camelia', 'azalea', 'hiedra',
    'enredadera', 'trébol', 'violeta', 'jazmín', 'clavel', 'dalía', 'petunia', 'begonia', 'crisantemo', 'maravilla',
    'gardenia', 'gladiolo', 'laurel', 'romero', 'tomillo', 'salvia', 'menta', 'poleo', 'canela', 'clavo',
    'jengibre', 'cúrcuma', 'vainilla', 'jenjibre', 'eucalipto', 'quebracho', 'lapacho', 'ceibo', 'jacarandá', 'tipa',
    'mineral', 'hierro', 'oro', 'plata', 'cobre', 'estaño', 'plomo', 'zinc', 'níquel', 'aluminio',
    'azufre', 'carbón', 'grafito', 'diamante', 'esmeralda', 'rubí', 'zafiro', 'topacio', 'cuarzo', 'ámbar',
    'mármol', 'granito', 'basalto', 'pizarra', 'caliza', 'arcilla', 'salitre', 'yedra', 'apio', 'raíz',
  ],

  'Cuerpo Humano': [
    'cuerpo', 'cabeza', 'cráneo', 'cara', 'rostro', 'frente', 'sien', 'ceja', 'párpado', 'pestaña',
    'ojo', 'oculista', 'ojera', 'nariz', 'fosa', 'fosas', 'boca', 'labio', 'dentadura', 'diente',
    'muela', 'paladar', 'lengua', 'úlula', 'encía', 'mandíbula', 'mentón', 'barbilla', 'mejilla', 'cachete',
    'oreja', 'orejón', 'lóbulo', 'cuello', 'garganta', 'nuez', 'laringe', 'faringe', 'trapecio', 'nuca',
    'hombro', 'brazo', 'culebrilla', 'antebrazo', 'codo', 'muñeca', 'mano', 'palma', 'dorso', 'dedo',
    'pulgar', 'índice', 'anular', 'meñique', 'uña', 'pecho', 'tórax', 'espalda', 'cadera', 'cintura',
    'abdomen', 'ombligo', 'estómago', 'barriga', 'vientre', 'costado', 'costilla', 'columna', 'vértebra', 'coccyx',
    'muslo', 'pierna', 'rodilla', 'pantorrilla', 'gemelo', 'tobillo', 'pie', 'planta', 'talón', 'arco',
    'dedos', 'plantilla', 'hueso', 'esqueleto', 'cráneo', 'tibia', 'peroné', 'fémur', 'pelvis', 'escápula',
    'clavícula', 'omóplato', 'húmero', 'radio', 'cúbito', 'carpiano', 'falange', 'colágeno', 'articulación', 'músculo',
    'bíceps', 'tríceps', 'cuádriceps', 'pectoral', 'abdominal', 'deltoides', 'gemelo', 'tendón', 'ligamento', 'cartílago',
    'piel', 'epidermis', 'dermis', 'sangre', 'vena', 'arteria', 'pulso', 'pulmón', 'bronquio', 'alvéolo',
    'corazón', 'músculo', 'riñón', 'hígado', 'páncreas', 'intestino', 'duodeno', 'colon', 'vesícula', 'estómago',
    'bazo', 'médula', 'cerebro', 'cerebelo', 'neuron', 'neurona', 'nervio', 'medula', 'orina', 'sudor',
    'lágrima', 'saliva', 'moco', 'mucosa', 'cabello', 'mechón', 'cabellera', 'melena', 'pelo', 'vello',
    'ceja', 'pelo', 'barba', 'bigote', 'patilla', 'coleta', 'trenza', 'cola', 'frente', 'pecho',
  ],
};