// tools/themes/sociedad.mjs
// Listas curativas de palabras por tema (vida social, cultura y actividad).

export const sociedad = {
  Familia: [
    'madre', 'mamá', 'padre', 'papá', 'papi', 'mami', 'hijo', 'hija', 'hermano', 'hermana',
    'abuelo', 'abuela', 'nieto', 'nieta', 'tío', 'tía', 'sobrino', 'sobrina', 'primo', 'prima',
    'padrino', 'madrina', 'ahijado', 'ahijada', 'suegro', 'suegra', 'yerno', 'nuera', 'cuñado', 'cuñada',
    'esposo', 'esposa', 'marido', 'mujer', 'novio', 'novia', 'prometido', 'prometida', 'pareja', 'conyugue',
    'cónyuge', 'viudo', 'viuda', 'familia', 'pariente', 'parientes', 'linaje', 'clan', 'descendiente', 'antepasado',
    'ancestro', 'bisabuelo', 'bisabuela', 'tatara', 'gemelo', 'gemela', 'mellizo', 'melliza', 'únic', 'primogénito',
    'bebé', 'bebito', 'criatura', 'pequeño', 'chiquitín', 'crianza', 'adopción', 'adoptado', 'huerfano', 'huérfano',
    'maternidad', 'paternidad', 'parentesco', 'hermandad', 'apellido', 'linaje', 'sangre', 'raíces', 'vínculo', 'lazo',
    'caserío', 'progenie', 'estirpe', 'paz', 'hogar', 'quinta', 'recría', 'nuera', 'cuñado', 'sobrino',
  ],

  Profesiones: [
    'médico', 'médica', 'doctor', 'doctora', 'cirujano', 'dentista', 'enfermero', 'enfermera', 'farmacéutico', 'paramédico',
    'abogado', 'abogada', 'juez', 'jueza', 'fiscal', 'notario', 'procurador', 'forense', 'policía', 'detective',
    'guardia', 'agente', 'soldado', 'militar', 'oficial', 'piloto', 'aeronauta' , 'azafata', 'copiloto', 'marinero',
    'capitán', 'timonel', 'maquinista', 'conductor', 'chofer', 'taxista', 'camionero', 'colectivero', 'cartero', 'repartidor',
    'profesor', 'profesora', 'maestro', 'maestra', 'tutor', 'rector', 'director', 'bibliotecario', 'científico', 'investigador',
    'ingeniero', 'arquitecto', 'diseñador', 'electricista', 'plomero', 'fontanero', 'carpintero', 'albañil', 'obrero', 'pintor',
    'soldador', 'herrero', 'cerrajero', 'tornero', 'mecánico', 'carpintero', 'vidriero', 'tejedor', 'sastre', 'modista',
    'zapatero', 'panadero', 'pastelero', 'cocinero', 'chef', 'cocina', 'mesero', 'camarero', 'restaurador', 'barman',
    'agricultor', 'granjero', 'campesino', 'ganadero', 'vaquero', 'pescador', 'leñador', 'jardinero', 'florista', 'apicultor',
    'comerciante', 'vendedor', 'dependiente', 'cajero', 'contable', 'contador', 'auditor', 'banquero', 'inversor', 'agente',
    'asesor', 'consultor', 'gerente', 'administrador', 'secretaria', 'secretario', 'recepcionista', 'operador', 'telefonista', 'digitador',
    'programador', 'informático', 'sistemista', 'técnico', 'analista', 'diseñador', 'publicista', 'marketer', 'economista', 'físico',
    'químico', 'biólogo', 'geólogo', 'astrónomo', 'matemático', 'historiador', 'arqueólogo', 'antropólogo', 'sociólogo', 'psicólogo',
    'psiquiatra', 'terapeuta', 'veterinario', 'zootecnista', 'periodista', 'reportero', 'redactor', 'editor', 'escritor', 'novelista',
    'poeta', 'traductor', 'interprete', 'locutor', 'presentador', 'actor', 'actriz', 'bailarín', 'cantante', 'músico',
    'director', 'productor', 'fotógrafo', 'cámara', 'camarógrafo', 'pintor', 'escultor', 'dibujante', 'ilustrador', 'animador',
    'deportista', 'atleta', 'entrenador', 'árbitro', 'futbolista', 'baloncestista', 'portero', 'arquero', 'nadador', 'corredor',
    'socorerista', 'apicultor', 'minero', 'plataformista', 'petrolero', 'pescadero', 'verdulero', 'frutero', 'carnicero', 'lechero',
  ],

  Casa: [
    'casa', 'casita', 'chozo', 'cabaña', 'chalet', 'villa', 'palacete', 'mansión', 'palacio', 'castillo',
    'torre', 'rascacielos', 'edificio', 'piso', 'departamento', 'apartamento', 'estudio', 'loft', 'duplex', 'vivienda',
    'hogar', 'morada', 'domicilio', 'residencia', 'sala', 'salón', 'comedor', 'cocina', 'baño', 'aseo',
    'lavabo', 'ducha', 'bañera', 'jacuzzi', 'dormitorio', 'cuarto', 'alcoba', 'recámara', 'habitación', 'despacho',
    'estudio', 'biblioteca', 'sótano', 'ático', 'azotea', 'terraza', 'balcón', 'galería', 'patio', 'jardín',
    'garaje', 'cochera', 'desván', 'trastero', 'bodega', 'pasillo', 'escalera', 'escalón', 'baranda', 'pasamanos',
    'puerta', 'portón', 'cerradura', 'cerrojo', 'picaporte', 'manilla', 'bisagra', 'ventana', 'ventanal', 'claraboya',
    'persiana', 'cortina', 'cortina', 'suelo', 'piso', 'techo', 'tejado', 'muro', 'pared', 'tabique', 'divisorio',
    'vigas', 'columna', 'pilar', 'cimientos', 'cimiento', 'losas', 'azulejo', 'mosaico', 'losa', 'ladrillo',
    'teja', 'cemento', 'hormigón', 'yeso', 'estuco', 'pintura', 'barniz', 'esmalte', 'empapelado', 'parquet',
    'mesa', 'mesita', 'silla', 'sillón', 'banco', 'banco', 'banqueta', 'taburete', 'sofá', 'butaca',
    'cama', 'colchón', 'almohada', 'cojín', 'edredón', 'frazada', 'sábana', 'colcha', 'mantel', 'mantita',
    'armario', 'ropero', 'closet', 'cómoda', 'cajonera', 'estante', 'repisa', 'anaquel', 'perchero', 'colgador',
    'espejo', 'cuadro', 'mueble', 'lámpara', 'candelabro', 'foco', 'bulbo', 'aplique', 'lámina', 'adorno',
    'estufa', 'horno', 'microondas', 'nevera', 'refrigerador', 'frigorífico', 'congelador', 'lavadora', 'lavavajillas', 'tostadora',
    'olla', 'cacerola', 'sartén', 'cazuela', 'tapa', 'plato', 'vajilla', 'taza', 'botella', 'vaso',
    'copa', 'jarra', 'cubiertos', 'tenedor', 'cuchara', 'cucharita', 'cuchillo', 'cuchillito', 'servilleta', 'bandeja',
    'escombros', 'fregadero', 'desagüe', 'cañería', 'tubería', 'grifo', 'canilla', 'llave', 'válvula', 'bombona',
  ],

  Ropa: [
    'camisa', 'camison', 'polera', 'polo', 'remera', 'playera', 'blusa', 'túnica', 'blusón', 'suéter',
    'sudadera', 'buzo', 'jersey', 'chaleco', 'abrigo', 'chaqueta', 'cazadora', 'parka', 'impermeable', 'poncho',
    'pantalón', 'pantalones', 'jeans', 'vaqueros', 'mahones', 'piloches', 'bermuda', 'shorts', 'baggy', 'leggins',
    'falda', 'minifalda', 'vestido', 'traje', 'esmoquin', 'saco', 'blazer', 'americana', 'chaqueta', 'guayabera',
    'camiseta', 'camisón', 'pijama', 'bata', 'albornoz', 'abanico', 'medias', 'calcetín', 'calcetines', 'soquetes',
    'leotardo', 'malla', 'bikini', 'top', 'sostén', 'corpiño', 'sujetador', 'calzoncillo', 'calzón', 'braguita',
    'ropa', 'vestimenta', 'atuendo', 'indumentaria', 'prenda', 'camisa', 'cuello', 'manga', 'puño', 'botón',
    'cremallera', 'cierre', 'ciper', 'cinturón', 'cinto', 'comba', 'hebilla', 'correa', 'tirantes', 'banda',
    'sombrero', 'gorra', 'boina', 'gorro', 'casco', 'pañoleta', 'pañuelo', 'bufanda', 'capucha', 'turbante',
    'zapato', 'zapatilla', 'tenis', 'bota', 'botín', 'sandalias', 'sandalia', 'chancleta', 'chancla', 'pegamento',
    'taco', 'suela', 'cordón', 'agujeta', 'medias', 'mocasín', 'zueco', 'alpargata', 'huarache', 'deporte',
    'guante', 'guantes', 'mitones', 'arete', 'arete', 'collar', 'colgante', 'pulsera', 'brazalete', 'anillo',
    'reloj', 'broche', 'prendedor', 'insignia', 'alfiler', 'pinza', 'gema', 'joya', 'perla', 'esmalte',
  ],

  Transporte: [
    'auto', 'automóvil', 'coche', 'carro', 'vehículo', 'camión', 'camioneta', 'bus', 'autobús', 'ómnibus',
    'micro', 'colectivo', 'tranvía', 'metro', 'subte', 'tren', 'ferrocarril', 'vagón', 'locomotora', 'andén',
    'avión', 'aeroplano', 'helicóptero', 'hidroavión', 'jet', 'globo', 'dirigible', 'planeador', 'ultraligero', 'avioneta',
    'barco', 'buque', 'velero', 'yate', 'lancha', 'bote', 'canoa', 'kayak', 'góndola', 'pangas',
    'canal', 'ferry', 'transbordador', 'crucero', 'barcaza', 'tranvía', 'patineta', 'patín', 'monopatín', 'scooter',
    'bicicleta', 'bici', 'ciclomotor', 'motocicleta', 'moto', 'ciclomoto', 'sidecar', 'triciclo', 'remolque', 'carreta',
    'carruaje', 'calesa', 'carroza', 'cuatriciclo', 'quad', 'buggy', 'tabla', 'surf', 'remolcador', 'tractor',
    'góndola', 'teleférico', 'funicular', 'cable', 'ascensor', 'escalera', 'rampa', 'pasarela', 'túnel', 'viaducto',
    'puente', 'carretera', 'autopista', 'avenida', 'calle', 'bulevar', 'camino', 'ruta', 'vía', 'sendero',
    'semáforo', 'señal', 'señalética', 'rotonda', 'cruce', 'peaje', 'gasolinera', 'bomba', 'suridor', 'estacionamiento',
    'garaje', 'puerto', 'aeropuerto', 'terminal', 'estación', 'embarcadero', 'muelle', 'dársena', 'hangar', 'pista',
    'volante', 'timón', 'manillar', 'pedal', 'freno', 'clutch', 'palanca', 'acelerador', 'embrague', 'marcha',
    'neumático', 'llanta', 'goma', 'rueda', 'rin', 'vidrio', 'parabrisas', 'cristal', 'espejo', 'foco',
  ],

  Ciudad: [
    'ciudad', 'pueblo', 'villa', 'aldea', 'metrópolis', 'barrio', 'colonia', 'parroquia', 'localidad', 'pedanía',
    'capital', 'centro', 'periferia', 'extrarradio', 'afueras', 'zona', 'sector', 'manzana', 'cuadras', 'glorieta',
    'plaza', 'parque', 'jardín', 'bulevar', 'alameda', 'paseo', 'esplanada', 'malecón', 'costanera', 'quebrada',
    'avenida', 'calle', 'callejón', 'travesía', 'pasaje', 'giro', 'esquina', 'bocacalle', 'cruce', 'vereda',
    'acera', 'banqueta', 'andador', 'peatón', 'peatonal', 'circular', 'rotonda', 'plaza', 'fuente', 'obelisco',
    'monumento', 'estatua', 'busto', 'escultura', 'catedral', 'iglesia', 'basílica', 'templo', 'capilla', 'santuario',
    'edificio', 'ayuntamiento', 'municipio', 'alcaldía', 'gobernación', 'juzgado', 'tribunal', 'comisaría', 'cuartel', 'prisión',
    'cárcel', 'penitenciaría', 'hospital', 'clínica', 'sanatorio', 'consultorio', 'farmacia', 'centro', 'escuela', 'instituto',
    'colegio', 'universidad', 'facultad', 'liceo', 'museo', 'galería', 'teatro', 'cine', 'anfiteatro', 'estadio',
    'estadio', 'cancha', 'polideportivo', 'gimnasio', 'piscina', 'biblioteca', 'archivo', 'hemeroteca', 'auditorio', 'sala',
    'mercado', 'tianguis', 'feria', 'puesto', 'kiosko', 'tienda', 'almacén', 'supermercado', 'hipermercado', 'bazar',
    'banco', 'sucursal', 'oficina', 'fábrica', 'industria', 'taller', 'almacén', 'depósito', 'almacenes', 'granero',
    'hotel', 'hostal', 'posada', 'motel', 'residencial', 'apartamento', 'casa', 'torre', 'mirador', 'atalaya',
    'parada', 'terminal', 'mercado', 'fuente', 'surtidor', 'café', 'restaurante', 'restobar', 'librería', 'papelería',
    'florería', 'panadería', 'carnicería', 'pescadería', 'frutería', 'verdulería', 'peluquería', 'barbería', 'perfumería', 'joyería',
  ],

  Educación: [
    'escuela', 'colegio', 'instituto', 'liceo', 'academia', 'universidad', 'facultad', 'carrera', 'aula', 'salón',
    'clase', 'lección', 'curso', 'semestre', 'trimestre', 'año', 'ciclo', 'grado', 'nivel', 'sección',
    'estudiante', 'alumno', 'alumna', 'alumnado', 'escolar', 'universitario', 'graduado', 'titulado', 'buzón', 'becario',
    'practicante', 'aprendiz', 'mentor', 'profesor', 'maestro', 'docente', 'pedagogo', 'educador', 'orientador', 'tutor',
    'director', 'rector', 'decano', 'coordinador', 'preceptor', 'bibliotecario', 'conserje', 'laboral', 'beca', 'ayuda',
    'asignatura', 'materia', 'taller', 'laboratorio', 'ciencias', 'letras', 'idioma', 'gramática', 'ortografía', 'cálculo',
    'álgebra', 'geometría', 'trigonometría', 'física', 'química', 'biología', 'historia', 'geografía', 'filosofía', 'ética',
    'matemática', 'estadística', 'lógica', 'informática', 'música', 'arte', 'dibujo', 'pintura', 'gimnasia', 'deporte',
    'libro', 'texto', 'cuaderno', 'cuadra', 'hoja', 'mimo', 'lápiz', 'lapicera', 'bolígrafo', 'pluma',
    'borrador', 'goma', 'sacapuntas', 'regla', 'escuadra', 'compás', 'calculadora', 'diccionario', 'enciclopedia', 'manual',
    'pizarrón', 'pizarra', 'marcador', 'marcador', 'tiza', 'silencio', 'carpeta', 'folder', 'carpet', 'archivador',
    'examen', 'parcial', 'prueba', 'evaluación', 'test', 'quiz', 'tarea', 'ejercicio', 'trabajo', 'proyecto',
    'deber', 'repaso', 'apuntes', 'resumen', 'síntesis', 'ensayo', 'monografía', 'tesis', 'dictado', 'lectura',
    'aprender', 'estudiar', 'repasar', 'memorizar', 'entender', 'comprender', 'investigar', 'averiguar', 'razonar', 'resolver',
  ],

  Música: [
    'música', 'canción', 'tema', 'melodía', 'ritmo', 'compás', 'nota', 'notas', 'pentagrama', 'clave',
    'acorde', 'tono', 'timbre', 'escala', 'tonalidad', 'armonía', 'contrapunto', 'sinfonía', 'concierto', 'ópera',
    'tango', 'vals', 'bolero', 'cumbia', 'salsa', 'merengue', 'reggaetón', 'rock', 'pop', 'jazz',
    'blues', 'soul', 'funk', 'disco', 'rap', 'hiphop', 'country', 'metal', 'punk', 'folk',
    'coro', 'cuarteto', 'orquesta', 'banda', 'grupo', 'trío', 'dúo', 'cantante', 'cantor', 'cantautor',
    'vocalista', 'solista', 'compositor', 'director', 'maestro', 'músico', 'intérprete', 'tecladista', 'guitarrista', 'bajista',
    'percusionista', 'violinista', 'cellista', 'flautista', 'pianista', 'drummer', 'baterista', 'saxofonista', 'clarinete', 'oboeista',
    'guitarra', 'guitarrón', 'bajo', 'violín', 'viola', 'cello', 'violonchelo', 'arpa', 'piano', 'teclado',
    'órgano', 'acordeón', 'bandoneón', 'flauta', 'pífano', 'oboe', 'fagot', 'clarinete', 'trompeta', 'corneta',
    'trombón', 'tuba', 'saxofón', 'saxo', 'pandereta', 'pandero', 'tambor', 'tamboril', 'bombo', 'platillos',
    'bongó', 'congas', 'maracas', 'claves', 'marimba', 'xilófono', 'campana', 'cascabel', 'triángulo', 'castañuelas',
    'micrófono', 'equipo', 'bocina', 'audífono', 'tornamesa', 'vinilo', 'disco', 'compac', 'casete', 'playlist',
  ],

  Arte: [
    'arte', 'artista', 'pintura', 'pintar', 'cuadro', 'obra', 'lienzo', 'bastidor', 'lápiz', 'carboncillo',
    'acrílico', 'óleo', 'acuarela', 'temple', 'pigmento', 'tinta', 'pastel', 'craquela', 'fresco', 'mural',
    'muralista', 'retrato', 'paisaje', 'naturaleza', 'bodegón', 'marinas', 'desnudo', 'abstracción', 'colorista', 'dibujo',
    'boceto', 'esbozo', 'croquis', 'perfil', 'silueta', 'contorno', 'delineado', 'garabato', 'caricatura', 'viñeta',
    'cómic', 'manga', 'ilustración', 'cartel', 'afiche', 'estampa', 'grabado', 'litografía', 'grabador', 'calcografía',
    'escultura', 'escultor', 'estatua', 'busto', 'torso', 'relieve', 'alto', 'bajorrelieve', 'busto', 'piedra',
    'mármol', 'bronce', 'arcilla', 'barro', 'cerámica', 'alfarería', 'esmalte', 'vitral', 'vidriera', 'mosaico',
    'fotografía', 'foto', 'instantánea', 'revelado', 'cámara', 'lente', 'objetivo', 'molote', 'veladura', 'encuadre',
    'diseño', 'diseñador', 'moda', 'ilustrador', 'tipografía', 'logotipo', 'logo', 'empaque', 'cromática', 'estética',
    'museo', 'galería', 'pinacoteca', 'exposición', 'vernissage', 'colección', 'obra', 'obra', 'creación', 'obra',
    'creatividad', 'inspiración', 'imaginar', 'representar', 'expresar', 'componer', 'esculpir', 'modelar', 'fotografiar', 'decorar',
  ],

  Tecnología: [
    'computadora', 'computador', 'ordenador', 'portátil', 'laptop', 'notebook', 'tablet', 'pantalla', 'monitor', 'teclado',
    'ratón', 'mousse', 'pad', 'impresora', 'escáner', 'proyector', 'grafito', 'tecnología', 'programa', 'software',
    'aplicación', 'app', 'programa', 'sistema', 'red', 'internet', 'web', 'página', 'sitio', 'servidor',
    'nube', 'correo', 'mensaje', 'chat', 'foro', 'blog', 'wiki', 'red', 'perfil', 'usuario',
    'contraseña', 'clave', 'usuario', 'cuenta', 'datos', 'archivo', 'fichero', 'carpeta', 'documento', 'documento',
    'información', 'pixel', 'código', 'código', 'lenguaje', 'byte', 'bit', 'giga', 'mega', 'procesador',
    'chip', 'microchip', 'tarjeta', 'memoria', 'disco', 'almacenamiento', 'cable', 'cargador', 'batería', 'pila',
    'energía', 'voltaje', 'electricidad', 'electrónica', 'circuito', 'placa', 'diodo', 'transistor', 'led', 'láser',
    'óptica', 'sensor', 'antena', 'señal', 'microfono', 'micrófono', 'audio', 'video', 'bluetooth', 'wifi',
    'wifi', 'fast', 'telefono', 'teléfono', 'celular', 'móvil', 'smartphone', 'reloj', 'gps', 'navegador',
    'mapa', 'traductor', 'asistente', 'robot', 'dron', 'vehículo', 'auto', 'coche', 'dato', 'cifra',
    'realidad', 'virtual', 'aumentada', 'impresión', 'fibra', 'satélite', 'orbita', 'plataforma', 'inteligencia', 'artificial',
  ],

  Deportes: [
    'deporte', 'fútbol', 'futbol', 'balompié', 'balón', 'futbolín', 'basquet', 'básquet', 'baloncesto', 'balonmano',
    'handball', 'tenis', 'pádel', 'squash', 'frontón', 'bádminton', 'pingpong', 'ping-pong', 'voleibol', 'vóley',
    'ha futbol', 'rugby', 'americano', 'béisbol', 'beisbol', 'soficial', 'críquet', 'golf', 'hockey', 'polo',
    'natación', 'nadar', 'buceo', 'submarinismo', 'apnea', 'crawl', 'espalda', 'mariposa', 'sincronizada', 'waterpolo',
    'atletismo', 'carrera', 'correr', 'velocista', 'sprint', 'maratón', 'triatlón', 'decatlón', 'salto', 'jabalina',
    'disco', 'peso', 'martillo', 'garrocha', 'vallas', 'equitación', 'hípica', 'salto', 'derby', 'galope',
    'ciclismo', 'bici', 'mountain', 'velódromo', 'motociclismo', 'motocross', 'fórmula', 'rally', 'drift', 'automovilismo',
    'boxeo', 'boxeador', 'guantes', 'casting', 'judo', 'yudo', 'karate', 'karaté', 'taekwondo', 'kungfu',
    'lucha', 'esgrima', 'judo', 'sambo', 'capoeira', 'artes', 'escalada', 'montañismo', 'senderismo', 'excursionismo',
    'rappel', 'paracaidismo', 'parapente', 'ala', 'planeo', 'vela', 'hípica', 'rafting', 'kayak', 'piragüismo',
    'remo', 'canoa', 'patinaje', 'patinar', 'rollers', 'patineta', 'tabla', 'snowboard', 'esquí', 'skiing',
    'trineo', 'bobsleigh', 'patinaje', 'hielo', 'curling', 'zumba', 'yoga', 'pilates', 'gimnasia', 'acrobacia',
    'juego', 'partido', 'campeonato', 'olimpiada', 'medalla', 'trofeo', 'copa', 'liga', 'torneo', 'marcador',
  ],
};